version: "3.8"
services:
  partial_project_tests_mysql:
    image: mysql:latest
    container_name: partial_project_tests_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=store
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - lab4-db:/var/lib/mysql
    networks:
      - lab4-network
  mongodb_tests:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    networks:
      - lab4-network
volumes:
  mongo:
  lab4-db:
networks:
  lab4-network: